name: Build MongoDB Server

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
      docker_tag:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-server:
    name: Build MongoDB Server
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build MongoDB Server Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.mongodb-server
        tags: ${{ inputs.docker_image }}:${{ inputs.docker_tag }}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BASE_IMAGE=ghcr.io/${{ github.repository }}/mongodb-drivers:latest 