name: Docker Build Pipeline

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
      docker_tag:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-drivers:
    uses: ./.github/workflows/docker-build-drivers.yml
    with:
      docker_image: ghcr.io/${{ github.repository }}/mongodb-drivers
      docker_tag: latest

  build-server:
    needs: build-drivers
    uses: ./.github/workflows/docker-build-server.yml
    with:
      docker_image: ghcr.io/${{ github.repository }}/mongodb-server
      docker_tag: latest

  build-app:
    needs: build-server
    uses: ./.github/workflows/docker-build-app.yml
    with:
      docker_image: ${{ inputs.docker_image }}
      docker_tag: ${{ inputs.docker_tag }}

