name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - '**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build.yml